### ISSUE TITLE
A `.key` attribute on time zones.

### ISSUE THREAD

**Issue by regebro** [pganssle/pytz-deprecation-shim#26]
I'm thinking of using `pytz_deprecation_shim` for `tzlocal`, to provide less of a shock for people who expect pytz objects. However, the wrapped objects doesn't have a `.key` attribute, as ZoneInfo objects do, forcing my tests to use the `.zone` attribute and hence having LOADS of warnings. :-)

So I'd like a `.key` attribute, please. 

I'm happy to make a PR implementing this, if you think it's a good idea.

**Comment by pganssle** [comment]
Hmm... I am not super in favor of this. The idea isn't that you are supposed to use this long term, it's to prevent blindsiding people who are using `pytz`. If you are someone who already knows up use `zoneinfo`, there's no reason to use these zones at all, you should either construct `zoneinfo` zones directly or, if you are getting zones that may be from this library, `pytz`, `zoneinfo` or `dateutil`, you can use [`upgrade_tzinfo`](https://pytz-deprecation-shim.readthedocs.io/en/latest/helpers.html#pytz_deprecation_shim.helpers.upgrade_tzinfo) to get a `zoneinfo ` zone.

Alternatively, you can use `str`, which has similar semantics for both `zoneinfo` and `pytz`.

That said, I understand your use case is an unusual one - you didn't do it the right way to start with, and now you want something that is both backwards *and* forwards compatible with `zoneinfo` and backwards compatible with `pytz`. It may be worth implementing this, but we'd want to raise warnings with the use of `key` as well, since we'd want people to be explicitly getting `zoneinfo` zones anyway.

I'll have to think more about what it would take to be properly backwards compatible with both, and whether it's worth it for such a niche use case.

**Comment by regebro** [comment]
Yeah, but if you are using `tzlocal`, and you are using the zone attribute, it means you can't convert to using the key attribute, because the timezone you get from `tzlocal` won't have a key attribute.

"you didn't do it the right way to start with"

Although that's true, it wouldn't have mattered. To transition away from pytz, the timezones that are returned need to be 100% compatible with zoneinfo, or the transition isn't possible.

"now you want something that is both backwards and forwards compatible with zoneinfo and backwards compatible with pytz"

Yup.

"it may be worth implementing this, but we'd want to raise warnings with the use of key as well, since we'd want people to be explicitly getting zoneinfo zones anyway."

But zoneinfo zones has a key attribute, so I'm not sure what you would be warning about?

**Comment by pganssle** [comment]
I think you may be slightly misunderstanding what this library is for. It's not a *long term replacement* for `pytz`, it's a short-term replacement intended for people who provide an API that used to emit `pytz` time zones and will eventually emit a time zone that uses the standard `tzinfo` interface with PEP 495 and all that jazz.

The way it's supposed to be applied would be, to take `tzlocal` 2.x as an example:

1. `tzlocal` 2.x: Emits `pytz` zones, has a large number of users, many of whom rely on `pytz`-specific aspects of `pytz`'s interface, like `.localize` or `.zone`.
2. `tzlocal` 3.0: Emits `pytz-deprecation-shim` zones, which act just like `pytz` zones *when you use them like `pytz` zones*, but if you start using them like `tzinfo` zones, they work like standard-issue zones. These emit deprecation warnings if you treat them like `pytz` zones so that end users can make an affirmative decision to do something different.
3. `tzlocal` 4.0: Emits `zoneinfo.ZoneInfo` zones.

The reason you in `pytz-deprecation-shim` in 3.0 is for all the people who have code that is still expecting `pytz` zones. Once those people know that `pytz` zones are deprecated and start making affirmative decisions about what to do, _they no longer need the shims_, and can and probably _should_ de-shim the zones and affirmatively switch to `zoneinfo`. They don't need perfect forwards-and-backwards compatibility because they can choose to no longer require backwards compatibility with `pytz`.

> Yeah, but if you are using `tzlocal`, and you are using the zone attribute, it means you can't convert to using the key attribute, because the timezone you get from `tzlocal` won't have a key attribute.

Yes, and if you need the `key` attribute you need to *know* that you have a `zoneinfo.ZoneInfo` zone, so presumably you should either use `tzlocal.get_localzone_name` and pass it to `zoneinfo.ZoneInfo` or you can use [`upgrade_tzinfo`](https://pytz-deprecation-shim.readthedocs.io/en/latest/helpers.html#pytz_deprecation_shim.helpers.upgrade_tzinfo) to ensure that you have a `zoneinfo.ZoneInfo` zone *regardless of what version of `tzlocal` you have:

```python
>>> import pytz_deprecation_shim
>>> import tzlocal
>>> # Simulate the logic after tzlocal adopts pytz_deprecation_shim
>>> tz_shim = pytz_deprecation_shim.wrap_zone(tzlocal.get_localzone())
>>> tz_shim
_PytzShimTimezone(zoneinfo.ZoneInfo(key='America/New_York'), 'America/New_York')
>>> pytz_deprecation_shim.helpers.upgrade_tzinfo(tz_shim)
zoneinfo.ZoneInfo(key='America/New_York')
```

One thing to note is that this only really applies in Python 3. `pytz-deprecation-shim` also supports Python 2.x, even though there is no `zoneinfo` backport to Python 2. In Python 2, `pytz-deprecation-shim` returns a `dateutil` time zone, which doesn't have a `key`.


> But zoneinfo zones has a key attribute, so I'm not sure what you would be warning about?

It's probably fair that a warning isn't entirely necessary, but I don't like the idea of migrating people away from one non-standard way of working with `tzinfo` objects to another. `zoneinfo.ZoneInfo` objects have a `key` element for serialization purposes, but in most APIs you should prefer to accept generic `tzinfo` rather than `zoneinfo.ZoneInfo`. That allows you to accept `datetime.timezone.utc`, for example, which doesn't have a `.key` element because such an element doesn't make sense in that context.

If I were to add a warning, I would say, "You seem to be using `zoneinfo`-specific functionality, please explicitly upgrade to `zoneinfo` rather than continuing to use this shim." Doing so would improve compatibility with `zoneinfo` in the long run, because of the [identity-specific semantics of time zone math in Python](https://www.python.org/dev/peps/pep-0615/#id7).

**Comment by regebro** [comment]
For a library, short term is a year or two, which may be long term for others. :-)

Anyway, it might be better if I implement my own shim. People who use the pytz `zone` attribute with tzlocal would likely to that to get the resulting timezone, and in the next version I will have a specific API call for that, so it might be better for me to tell them about that call instead.

**Comment by pganssle** [comment]
> Anyway, it might be better if I implement my own shim. People who use the pytz zone attribute with tzlocal would likely to that to get the resulting timezone, and in the next version I will have a specific API call for that, so it might be better for me to tell them about that call instead.

Certainly up to you! Though I will warn you it's trickier than it seems to do this right. Even this library is a bit of a compromise, as you can see from the migration guide.

I'd probably be open to making the warning and error behavior and messages more configurable so it's easier for libraries to adapt this library to their own needs. The main downside to that would be that shimmed time zones would not be identical across libraries, but I think you lose that property across libraries anyway when some migrate away from pytz and others don't.

For `tzlocal` users (Python 3-only, no unusual zones read from a file or anything), I think `str()` is equivalent to both `.zone` and `.key`, so this may be a reasonable compromise as well for most users.

**Comment by regebro** [comment]
I could also just add a `.key`, either directly to any zone I return, or to the shim class. A bit hacky, but certainly less work. 🤔

**Comment by pganssle** [comment]
> I could also just add a `.key`, either directly to any zone I return, or to the shim class. A bit hacky, but certainly less work.

I would recommend against doing any manipulation to the actual zones you return, because each zone is a singleton:

```python
>>> import pytz_deprecation_shim
>>> tz1 = pytz_deprecation_shim.timezone("America/New_York")
>>> tz2 = pytz_deprecation_shim.timezone("America/New_York")
>>> tz1 is tz2
True
```

If you modify the attributes of a given zone, then anyone *else* using `pytz_deprecation_shim` will also suddenly have their zones mutated out from under them, which is not ideal. The shim class itself is also private, and generally not constructed from its constructor anyway, so I do not recommend the subclassing route.

Like I said, getting the semantics right on this was actually a bit tricky. Considering that you made much more significant breaking changes in the 2.x → 3.x migration and the 3.x release wasn't too long ago, it _may_ be preferable to do a 4.x release just switching to `pytz_deprecation_shim`. It does suck that the people who did the "right thing" and migrated directly to `zoneinfo` (including the use of `.key`) are the ones who are going to get hit with extra work, but on the other hand they are probably the people with the most flexible code bases in the first place.

If you do adopt `pytz_deprecation_shim` directly, I would recommend exposing `pytz_deprecation_shim.helpers.upgrade_tzinfo` somewhere in the `tzlocal` namespace, so that your users don't need to take their own dependency on `pytz_deprecation_shim`. You can do a 4.x release that both exposes a way to get the local time zone IANA key and exposes a `tzlocal.compat.to_zoneinfo` or something, then tell people to either migrate to the "get an IANA key" mechanism or to use the `to_zoneinfo` mechanism. When you remove `pytz_deprecation_shim`, you can also just make `to_zoneinfo` a no-op.

**Comment by regebro** [comment]
Whatever the next version will be, it won't require anyone to use `upgrade_tzinfo`. It will work with warnings for those using pytz, and they can then change their code to assume the objects are zoneinfo objects, and this will get rid of the warnings. In a future version of tzlocal, I will stop using the shim. 

If that includes monkey-patching in a `.key()` attribute, so be it.

Thanks for the feedback and constructive discussion on this.

**Comment by pganssle** [comment]
OK, up to you, but I have until now refrained from pointing out that _had you listened to me about this in the first place_, you wouldn't have had this problem. It _may_ be worth considering that by ignoring my advice on this topic again, you may once again be courting disaster.

**Comment by regebro** [comment]
I first heard about this shim last week. You mentioned it the day before I merged 3.0, but I seem to not have noticed that comment. It would indeed have been better if I had.

But anyway, hearing about it earlier would not have changed my mind on wanting a .key attribute.

You have not given me any arguments for why a .key attribute would create a disaster.

**Comment by pganssle** [comment]
@regebro Actually, I suggested it to you at least once, on September 20, 2020: https://github.com/regebro/tzlocal/issues/90#issuecomment-695831520

I gave very explicit warnings [later in the thread](https://github.com/regebro/tzlocal/issues/90#issuecomment-699688288), and went to some effort to publicize the change, [on my twitter feed](https://twitter.com/pganssle/status/1308042009341558791?s=20) as well as actively seeking out projects that depend on `tzlocal` and telling them about this ([e.g. maya](https://github.com/timofurrer/maya/issues/191)).

I also warned about this [on the PR implementing the change](https://github.com/regebro/tzlocal/pull/92#discussion_r492062528) and suggested `pytz-deprecation-shim` in [a direct response to you](https://github.com/regebro/tzlocal/pull/92#discussion_r492079773)

I was pretty clear about predicting _exactly what happened_, and had already prepared extensive resources on how to deal with it that you ignored.

A `.key` attribute here is not the only issue to be concerned about, I have not thought through the full implications of making `pytz-deprecation-shim` a drop-in replacement for `zoneinfo.ZoneInfo`, which is what would be necessary to get the kind of forward-and-backward compatibility that you *actually* want (which would be papered over by the addition of a `.key` attribute).

I do think that monkey-patching in a `key` attribute into the shim could easily create problems for _other packages_, because `pytz_deprecation_shim` creates *singleton objects*, meaning that if, for example, `pandas` migrates to using `pytz_deprecation_shim`, you would be mutating objects *created by `pandas`*, and specifically *only the objects produced by `tzlocal`* (so you'd get a bug only with `Europe/Berlin` or whatever, and only after `tzlocal` calls have been made — super frustrating to debug 😅).

In any case, I am not saying that this would be a major issue like it was last time, but I think you have dug yourself into a bit of a hole and I believe that what I'm asking you to do by not monkey-patching or trying to write your own backwards-and-forwards compatible shims is to briefly put down the shovel and stop digging. I'm not convinced that it's impossible to write such shims, or even that it's especially difficult, but I think it probably requires more thought than you are putting into it, based on your suggestions. Please don't take that to mean that I think you are being thoughtless or that this is a unique characteristic of yours, just that I've spent a _lot_ of time working on this and related things, and my overall impression of the space is, "It's complicated" and "Proceed with extreme caution".

**Comment by pganssle** [comment]
I would also like to emphasize that I do respect your work on this topic and your expertise. I am still very interested in [seeing `tzlocal`'s functionality included in `zoneinfo`](https://github.com/regebro/tzlocal/issues/90#issuecomment-630830156), and the only reason I haven't actively e-mailed you about it is that my to do list is enormously long and my time is extremely limited these days. So please don't think that I consider you some YOLO fly by night maintainer; rather, please take everything I'm saying here as just a call for caution. I don't want to play some "I told you so" game, but I do think that the fact that I was bringing up the problems that you are now working to fix _since before the PR was merged_ is decent evidence that I can at least sometimes recognize when caution is warranted (though, admittedly, I don't keep a record of all the times I urged caution and everything turned out fine...).

**Comment by regebro** [comment]
Yeah, I'm sorry I missed that comment suggesting this before the merge (or maybe I didn't miss it, didn't understand it and forgot, it's also possible, but I'm not usually that forgetful). That would definitely have been much better. The aim of it is apparently different from what I need, but I do think it's a good module, and would be good in this position as well. 

But there is no reason to cry over lost milk. The question is what to do now. And as mentioned, no matter if I had implemented this a year ago, or now, I still want a .key attribute, and I still think this shim should have it.
